### ISSUE TITLE
Unknow how to use some scripts

### ISSUE THREAD

**Issue by dirsors** [agehring80/CheatEngine#1]
How do I use the following scripts?
-First Merc
-Needle Address
-Num-: Item 5th pocket --
-Num+: Item 5th pocket ++

**Comment by agehring80** [comment]
Hi.
First of all, cool that you're interessted in tis old gem  ;-)
The script ist for CheatEngine and tested with GOG version of Jagged Alliance.

1. Open the game in DosBox and go to the BattleScreen where you already have a soldier.
2. Open CheatEngine and Attach to the DosBox Process.
3. Enable "Find and set symbols" !!!
4. Select a soldier in the BattleScreen. You need to hit key combo Crtl+E to get the 5 pocket vest.
5. With the + and - on the num block you scroll through the possible items in the game.
--> Take a look into the file ITEMS.TXT in this repo, to see all possible items.
--> Position 5 in the ITEMS.TXT = 45er Pis MOD
--> Click 5 times + on the numpad and you get item 5 in your 5th pocket of the vest.
Press I for inventory to update the view, always !!!

Needle Address is only for internal use (variables), to get the right memory addresses in the "Find and set Symbol" method.
The First Merc was only for debugging and should be not needed anymore.

Improvements are welcome ;-)

If you have further questions... or if you are satisfied with the answer... feedback is welcome.

**Comment by dirsors** [comment]
Ok, thank you very much for your assistance.
But the question is: If I want an item that is at 89 position, will I have to press 89 times the plus key?

**Comment by agehring80** [comment]
At the moment, this is the way to go (+ or - key to scroll through).
By the way, I fixed the scroll through function, that it remains in it's 'allowed' range.
The idea is, that you have all important items available as shortcut.
And if you need an item to resolve a quest or something alike (item only needed once or twice),
you can search for it in the catalogue.
Probably, it would be possible to create a gui where you can select the items...
like in a real catalogue. 
Sounds good.... Maybe I will implement something like this, when I find a timeslot for it.

**Comment by dirsors** [comment]
Thank you very much, my friend. I really like the Jagged Alliance Games and your script for CheatEngine is really great and useful. Unfortunately, I think that there isn't an option to get a "god mode" for mercs. Is this possible to create for the script?

**Comment by agehring80** [comment]
Possible... added. I left it out, because the game is a run through with disabled enemies, if god mode is active.
Did you find my JA2 script for Stracciatella ? agehring80/CheatEngine/tree/master/JaggedAlliance2 ?
It is also fun.

**Comment by agehring80** [comment]
After some testing I can say God Mode is mostly OK. In some situations the games mechanic requires that God Mode is disabled and the turn over "D" button is hit.
